version: "3.2"
services:
  frontend:
    image: styughjvbn/coco_frontend
    container_name: coco_frontend
    build:
      context: ./coco/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    stdin_open: true
