const BASE_URL = "http://localhost:8000";

export const API = {
  BASE_URL: BASE_URL,
  USER: `${BASE_URL}/user`,
  PERMISSION: `${BASE_URL}/user/permission`,
  FINDID: `${BASE_URL}/user/findid`,
  CHECKID: `${BASE_URL}/user/checkid`,
  UPDATEPW: `${BASE_URL}/user/pw`,
  AUTHROUTER: `${BASE_URL}/auth`,
  LOGIN: `${BASE_URL}/auth/login`,
  SIGNUP: `${BASE_URL}/auth/signup`,
  BOARD: `${BASE_URL}/boards/:board_id`,
  BOARDPATH: `${BASE_URL}/boards/:board_id`,
  BAORDLIKE: `${BASE_URL}/boards/:board_id/likes`,
  COMMENT: `${BASE_URL}/boards/:board_id/comments/:comment_id`,
  COMMENTLIKE: `${BASE_URL}/boards/:board_id/comments/:comment_id/likes`,
  IMAGE: `${BASE_URL}/image`,
  ROOM: `${BASE_URL}/rooms/:room_id`,
  ROOMQUESTION: `${BASE_URL}/rooms/:room_id/questions`,
  ROOMANSWER: `${BASE_URL}/rooms/:room_id/answer`,
  SELECTANSWER: `${BASE_URL}/rooms/:room_id/select-answer`,
  ROOMMYROOM: `${BASE_URL}/rooms/myroom`,
  ROOMMEMBER: `${BASE_URL}/rooms/:room_id/member`,
  ROOMROADMAP: `${BASE_URL}/rooms/:room_id/roadmaps/:roadmap_id`,
  NOTICE: `${BASE_URL}/notice`,
  MYSTATUS: `${BASE_URL}/my_status/:user_id`,
  TASK: `${BASE_URL}/tasks/:task_id`,
  CATEGORY: `${BASE_URL}/tasks/category`,
  MYPAGE: `${BASE_URL}/mypage/:user_id`,
  SUBMISSION: `${BASE_URL}/submission`,
  RESULT: `${BASE_URL}/result`,
  STATUS: `${BASE_URL}/status`,
  REQUESTTUTOR: `${BASE_URL}/request-tutor`,
  LINT: `${BASE_URL}/lint`,
  ALARM: `${BASE_URL}/user/alarm`,
  WPC: `${BASE_URL}/wpc/main`,
  LEVEL: `${BASE_URL}/user/level`,
  PLUGINSTATUS: `${BASE_URL}/plugin/status`,
  HOT: `${BASE_URL}/hot`,
  MYTASK: `${BASE_URL}/mytask`,
};
